import React, { Component } from "react";

export default class CloudInfraImg extends Component {
  render() {
    const theme = this.props.theme;
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="850"
        height="600"
        viewBox="0 0 850 600"
      >
        <title>Cloud and DevOps</title>

        {/* Ground shadow */}
        <ellipse
          cx="425"
          cy="560"
          rx="340"
          ry="30"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        {/* === Main Cloud Shape === */}
        <ellipse
          cx="425"
          cy="170"
          rx="180"
          ry="90"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <ellipse
          cx="310"
          cy="195"
          rx="100"
          ry="65"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <ellipse
          cx="540"
          cy="195"
          rx="100"
          ry="65"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <ellipse
          cx="425"
          cy="210"
          rx="220"
          ry="60"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        {/* Cloud outline */}
        <path
          d="M250,220 Q200,220 200,180 Q200,130 270,120 Q280,80 340,80 Q380,50 425,55 Q470,50 510,80 Q570,75 585,120 Q650,125 655,180 Q660,220 610,220 Z"
          fill="none"
          stroke={theme.imageHighlight}
          strokeWidth="2"
          opacity="0.8"
          strokeDasharray="6,4"
        />

        {/* AWS text inside cloud */}
        <text
          x="425"
          y="150"
          textAnchor="middle"
          fill={theme.text}
          fontSize="18"
          fontWeight="700"
          fontFamily="sans-serif"
          opacity="0.75"
        >
          Cloud
        </text>
        <text
          x="425"
          y="170"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Deploy . Scale . Monitor
        </text>

        {/* === Connection lines from cloud down === */}
        <line
          x1="320"
          y1="220"
          x2="180"
          y2="320"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          strokeDasharray="5,4"
          opacity="0.8"
        />
        <line
          x1="425"
          y1="220"
          x2="425"
          y2="320"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          strokeDasharray="5,4"
          opacity="0.8"
        />
        <line
          x1="530"
          y1="220"
          x2="670"
          y2="320"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          strokeDasharray="5,4"
          opacity="0.8"
        />

        {/* === Server Rack - Left === */}
        <rect
          x="130"
          y="320"
          width="100"
          height="130"
          rx="8"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="130"
          y="320"
          width="100"
          height="25"
          rx="8"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <text
          x="180"
          y="337"
          textAnchor="middle"
          fill={theme.text}
          fontSize="9"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          EC2
        </text>
        {/* Server rows */}
        <rect
          x="142"
          y="355"
          width="76"
          height="10"
          rx="3"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <circle
          cx="212"
          cy="360"
          r="3"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="142"
          y="372"
          width="76"
          height="10"
          rx="3"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <circle
          cx="212"
          cy="377"
          r="3"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="142"
          y="389"
          width="76"
          height="10"
          rx="3"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <circle
          cx="212"
          cy="394"
          r="3"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="142"
          y="406"
          width="76"
          height="10"
          rx="3"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <circle
          cx="212"
          cy="411"
          r="3"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="142"
          y="423"
          width="76"
          height="10"
          rx="3"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <circle
          cx="212"
          cy="428"
          r="3"
          fill={theme.imageHighlight}
          opacity="0.75"
        />

        {/* === CI/CD Pipeline - Center === */}
        <rect
          x="350"
          y="320"
          width="150"
          height="55"
          rx="10"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <text
          x="425"
          y="345"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          CI/CD Pipeline
        </text>
        <text
          x="425"
          y="362"
          textAnchor="middle"
          fill={theme.text}
          fontSize="8"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Build → Test → Deploy
        </text>

        {/* Pipeline stages */}
        <circle
          cx="370"
          cy="410"
          r="18"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="370"
          y="413"
          textAnchor="middle"
          fill={theme.text}
          fontSize="7"
          fontWeight="500"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Build
        </text>

        <line
          x1="388"
          y1="410"
          x2="406"
          y2="410"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          opacity="0.8"
        />
        <polygon
          points="404,407 410,410 404,413"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        <circle
          cx="425"
          cy="410"
          r="18"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="425"
          y="413"
          textAnchor="middle"
          fill={theme.text}
          fontSize="7"
          fontWeight="500"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Test
        </text>

        <line
          x1="443"
          y1="410"
          x2="461"
          y2="410"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          opacity="0.8"
        />
        <polygon
          points="459,407 465,410 459,413"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        <circle
          cx="480"
          cy="410"
          r="18"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <text
          x="480"
          y="413"
          textAnchor="middle"
          fill={theme.text}
          fontSize="7"
          fontWeight="500"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Deploy
        </text>

        {/* === Database - Right === */}
        <ellipse
          cx="670"
          cy="330"
          rx="55"
          ry="16"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="615"
          y="330"
          width="110"
          height="60"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <ellipse
          cx="670"
          cy="390"
          rx="55"
          ry="16"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <ellipse
          cx="670"
          cy="355"
          rx="55"
          ry="16"
          fill="none"
          stroke={theme.imageHighlight}
          strokeWidth="1"
          opacity="0.85"
        />
        <text
          x="670"
          y="365"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          RDS / DB
        </text>

        {/* === Docker Containers - Bottom Left === */}
        <rect
          x="100"
          y="480"
          width="160"
          height="65"
          rx="8"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        {/* Container boxes */}
        <rect
          x="115"
          y="492"
          width="35"
          height="35"
          rx="4"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <text
          x="132"
          y="514"
          textAnchor="middle"
          fill={theme.text}
          fontSize="7"
          fontFamily="sans-serif"
          opacity="0.75"
        >
          C1
        </text>
        <rect
          x="158"
          y="492"
          width="35"
          height="35"
          rx="4"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <text
          x="175"
          y="514"
          textAnchor="middle"
          fill={theme.text}
          fontSize="7"
          fontFamily="sans-serif"
          opacity="0.75"
        >
          C2
        </text>
        <rect
          x="201"
          y="492"
          width="35"
          height="35"
          rx="4"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <text
          x="218"
          y="514"
          textAnchor="middle"
          fill={theme.text}
          fontSize="7"
          fontFamily="sans-serif"
          opacity="0.75"
        >
          C3
        </text>
        <text
          x="180"
          y="542"
          textAnchor="middle"
          fill={theme.text}
          fontSize="9"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Docker
        </text>

        {/* Connection: Server to Docker */}
        <line
          x1="180"
          y1="450"
          x2="180"
          y2="480"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          strokeDasharray="4,3"
          opacity="0.75"
        />

        {/* === S3 Bucket - Bottom Center === */}
        <rect
          x="360"
          y="470"
          width="130"
          height="55"
          rx="10"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <text
          x="425"
          y="495"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          S3 Storage
        </text>
        {/* Bucket icon */}
        <rect
          x="397"
          y="505"
          width="56"
          height="8"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <rect
          x="401"
          y="510"
          width="48"
          height="4"
          rx="1"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        {/* Connection: Pipeline to S3 */}
        <line
          x1="425"
          y1="428"
          x2="425"
          y2="470"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          strokeDasharray="4,3"
          opacity="0.75"
        />

        {/* === Monitoring - Bottom Right === */}
        <rect
          x="580"
          y="440"
          width="140"
          height="80"
          rx="10"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <text
          x="650"
          y="462"
          textAnchor="middle"
          fill={theme.text}
          fontSize="9"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Monitoring
        </text>
        {/* Mini chart */}
        <polyline
          points="600,500 615,490 630,495 645,480 660,485 675,475 690,478 705,470"
          fill="none"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          opacity="0.85"
        />
        <line
          x1="600"
          y1="505"
          x2="705"
          y2="505"
          stroke={theme.imageHighlight}
          strokeWidth="0.5"
          opacity="0.85"
        />

        {/* Connection: DB to Monitoring */}
        <line
          x1="670"
          y1="406"
          x2="660"
          y2="440"
          stroke={theme.imageHighlight}
          strokeWidth="1.5"
          strokeDasharray="4,3"
          opacity="0.75"
        />

        {/* === Floating Labels === */}

        {/* AWS */}
        <rect
          x="60"
          y="230"
          width="60"
          height="26"
          rx="13"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="90"
          y="247"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          AWS
        </text>

        {/* Heroku */}
        <rect
          x="720"
          y="250"
          width="75"
          height="26"
          rx="13"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="757"
          y="267"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Heroku
        </text>

        {/* Vercel */}
        <rect
          x="720"
          y="470"
          width="70"
          height="26"
          rx="13"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="755"
          y="487"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Vercel
        </text>

        {/* Firebase */}
        <rect
          x="40"
          y="470"
          width="75"
          height="26"
          rx="13"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="77"
          y="487"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Firebase
        </text>

        {/* Nginx */}
        <rect
          x="60"
          y="390"
          width="60"
          height="26"
          rx="13"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="90"
          y="407"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          Nginx
        </text>

        {/* K8s */}
        <rect
          x="740"
          y="380"
          width="55"
          height="26"
          rx="13"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="767"
          y="397"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontWeight="600"
          fontFamily="sans-serif"
          opacity="0.8"
        >
          K8s
        </text>

        {/* Decorative upload/download arrows */}
        <polygon
          points="300,250 310,265 305,265 305,280 295,280 295,265 290,265"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <polygon
          points="550,280 560,265 555,265 555,250 545,250 545,265 540,265"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
      </svg>
    );
  }
}
