import React, { Component } from "react";

export default class FullStackImg extends Component {
  render() {
    const theme = this.props.theme;
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="900"
        height="600"
        viewBox="0 0 900 600"
      >
        <title>Full Stack Development</title>

        {/* Ground shadow */}
        <ellipse
          cx="450"
          cy="550"
          rx="360"
          ry="35"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        {/* Monitor */}
        <rect
          x="200"
          y="60"
          width="500"
          height="340"
          rx="16"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        {/* Screen inner */}
        <rect
          x="220"
          y="80"
          width="460"
          height="290"
          rx="8"
          fill={theme.body}
          stroke={theme.imageHighlight}
          strokeWidth="1"
          opacity="0.9"
        />
        {/* Monitor stand */}
        <rect
          x="400"
          y="400"
          width="100"
          height="50"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <rect
          x="350"
          y="445"
          width="200"
          height="12"
          rx="6"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        {/* Top bar (browser) */}
        <rect
          x="220"
          y="80"
          width="460"
          height="28"
          rx="8"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        {/* Browser dots */}
        <circle cx="240" cy="94" r="5" fill="#ff5f57" opacity="0.9" />
        <circle cx="258" cy="94" r="5" fill="#febc2e" opacity="0.9" />
        <circle cx="276" cy="94" r="5" fill="#28c840" opacity="0.9" />
        {/* URL bar */}
        <rect
          x="300"
          y="87"
          width="250"
          height="14"
          rx="7"
          fill={theme.imageHighlight}
          opacity="0.75"
        />

        {/* === Code Editor Left Panel === */}
        <rect
          x="230"
          y="118"
          width="200"
          height="240"
          rx="4"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        {/* File tree header */}
        <rect
          x="235"
          y="123"
          width="60"
          height="8"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.8"
        />

        {/* File tree items */}
        <rect
          x="245"
          y="140"
          width="45"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="255"
          y="152"
          width="70"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <rect
          x="255"
          y="164"
          width="55"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <rect
          x="255"
          y="176"
          width="65"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <rect
          x="245"
          y="192"
          width="50"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="255"
          y="204"
          width="60"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <rect
          x="255"
          y="216"
          width="75"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.85"
        />
        <rect
          x="245"
          y="232"
          width="40"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.75"
        />
        <rect
          x="255"
          y="244"
          width="55"
          height="6"
          rx="2"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        {/* === Code Editor Right Panel === */}
        <rect
          x="440"
          y="118"
          width="230"
          height="240"
          rx="4"
          fill={theme.imageHighlight}
          opacity="0.85"
        />

        {/* Line numbers */}
        <text
          x="450"
          y="140"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          1
        </text>
        <text
          x="450"
          y="153"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          2
        </text>
        <text
          x="450"
          y="166"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          3
        </text>
        <text
          x="450"
          y="179"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          4
        </text>
        <text
          x="450"
          y="192"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          5
        </text>
        <text
          x="450"
          y="205"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          6
        </text>
        <text
          x="450"
          y="218"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          7
        </text>
        <text
          x="450"
          y="231"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          8
        </text>
        <text
          x="450"
          y="244"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          9
        </text>
        <text
          x="447"
          y="257"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          10
        </text>
        <text
          x="447"
          y="270"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          11
        </text>
        <text
          x="447"
          y="283"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.8"
          fontFamily="monospace"
        >
          12
        </text>

        {/* Code lines - syntax highlighted */}
        <rect
          x="468"
          y="134"
          width="60"
          height="6"
          rx="2"
          fill="#c678dd"
          opacity="0.85"
        />
        <rect
          x="532"
          y="134"
          width="40"
          height="6"
          rx="2"
          fill="#e06c75"
          opacity="0.75"
        />
        <rect
          x="576"
          y="134"
          width="30"
          height="6"
          rx="2"
          fill="#61afef"
          opacity="0.75"
        />

        <rect
          x="478"
          y="147"
          width="45"
          height="6"
          rx="2"
          fill="#98c379"
          opacity="0.75"
        />
        <rect
          x="528"
          y="147"
          width="70"
          height="6"
          rx="2"
          fill="#d19a66"
          opacity="0.75"
        />

        <rect
          x="478"
          y="160"
          width="55"
          height="6"
          rx="2"
          fill="#61afef"
          opacity="0.75"
        />
        <rect
          x="538"
          y="160"
          width="35"
          height="6"
          rx="2"
          fill="#e5c07b"
          opacity="0.75"
        />
        <rect
          x="578"
          y="160"
          width="50"
          height="6"
          rx="2"
          fill="#98c379"
          opacity="0.75"
        />

        <rect
          x="488"
          y="173"
          width="80"
          height="6"
          rx="2"
          fill="#e06c75"
          opacity="0.75"
        />

        <rect
          x="488"
          y="186"
          width="50"
          height="6"
          rx="2"
          fill="#c678dd"
          opacity="0.75"
        />
        <rect
          x="543"
          y="186"
          width="65"
          height="6"
          rx="2"
          fill="#61afef"
          opacity="0.75"
        />

        <rect
          x="498"
          y="199"
          width="40"
          height="6"
          rx="2"
          fill="#d19a66"
          opacity="0.75"
        />
        <rect
          x="543"
          y="199"
          width="55"
          height="6"
          rx="2"
          fill="#98c379"
          opacity="0.75"
        />

        <rect
          x="488"
          y="212"
          width="70"
          height="6"
          rx="2"
          fill="#e5c07b"
          opacity="0.75"
        />

        <rect
          x="478"
          y="225"
          width="35"
          height="6"
          rx="2"
          fill="#c678dd"
          opacity="0.75"
        />

        <rect
          x="468"
          y="238"
          width="90"
          height="6"
          rx="2"
          fill="#61afef"
          opacity="0.75"
        />
        <rect
          x="563"
          y="238"
          width="40"
          height="6"
          rx="2"
          fill="#e06c75"
          opacity="0.85"
        />

        <rect
          x="478"
          y="251"
          width="60"
          height="6"
          rx="2"
          fill="#98c379"
          opacity="0.75"
        />

        <rect
          x="478"
          y="264"
          width="45"
          height="6"
          rx="2"
          fill="#d19a66"
          opacity="0.75"
        />
        <rect
          x="528"
          y="264"
          width="55"
          height="6"
          rx="2"
          fill="#e5c07b"
          opacity="0.85"
        />

        <rect
          x="468"
          y="277"
          width="50"
          height="6"
          rx="2"
          fill="#c678dd"
          opacity="0.75"
        />

        {/* Terminal at bottom of screen */}
        <rect
          x="230"
          y="330"
          width="440"
          height="30"
          fill={theme.imageHighlight}
          opacity="0.38"
        />
        <text
          x="240"
          y="348"
          fill={theme.imageHighlight}
          fontSize="8"
          opacity="0.85"
          fontFamily="monospace"
        >
          $ npm run dev
        </text>
        <rect
          x="315"
          y="343"
          width="6"
          height="10"
          fill={theme.imageHighlight}
          opacity="0.75"
        />

        {/* === Floating Tech Labels === */}

        {/* React badge - top left */}
        <rect
          x="100"
          y="100"
          width="70"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="135"
          y="118"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          React
        </text>
        <line
          x1="170"
          y1="114"
          x2="220"
          y2="130"
          stroke={theme.imageHighlight}
          strokeWidth="1"
          strokeDasharray="4,3"
          opacity="0.75"
        />

        {/* Node.js badge - right */}
        <rect
          x="710"
          y="140"
          width="80"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="750"
          y="158"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Node.js
        </text>
        <line
          x1="710"
          y1="154"
          x2="680"
          y2="170"
          stroke={theme.imageHighlight}
          strokeWidth="1"
          strokeDasharray="4,3"
          opacity="0.75"
        />

        {/* MongoDB badge - left */}
        <rect
          x="80"
          y="250"
          width="90"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="125"
          y="268"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          MongoDB
        </text>
        <line
          x1="170"
          y1="264"
          x2="220"
          y2="270"
          stroke={theme.imageHighlight}
          strokeWidth="1"
          strokeDasharray="4,3"
          opacity="0.75"
        />

        {/* Next.js badge - top right */}
        <rect
          x="720"
          y="230"
          width="80"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="760"
          y="248"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Next.js
        </text>
        <line
          x1="720"
          y1="244"
          x2="680"
          y2="260"
          stroke={theme.imageHighlight}
          strokeWidth="1"
          strokeDasharray="4,3"
          opacity="0.75"
        />

        {/* Docker badge - bottom left */}
        <rect
          x="120"
          y="420"
          width="75"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="157"
          y="438"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Docker
        </text>

        {/* Solana badge - bottom right */}
        <rect
          x="680"
          y="400"
          width="80"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="720"
          y="418"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Solana
        </text>

        {/* Rust badge */}
        <rect
          x="700"
          y="340"
          width="65"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="732"
          y="358"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Rust
        </text>

        {/* Git badge */}
        <rect
          x="100"
          y="340"
          width="55"
          height="28"
          rx="14"
          fill={theme.imageHighlight}
          opacity="0.28"
        />
        <text
          x="127"
          y="358"
          textAnchor="middle"
          fill={theme.text}
          fontSize="10"
          fontFamily="sans-serif"
          opacity="0.85"
        >
          Git
        </text>

        {/* Decorative brackets */}
        <text
          x="130"
          y="190"
          fill={theme.imageHighlight}
          fontSize="40"
          opacity="0.75"
          fontFamily="monospace"
        >
          {"{"}
        </text>
        <text
          x="740"
          y="310"
          fill={theme.imageHighlight}
          fontSize="40"
          opacity="0.75"
          fontFamily="monospace"
        >
          {"}"}
        </text>
        <text
          x="150"
          y="160"
          fill={theme.imageHighlight}
          fontSize="22"
          opacity="0.38"
          fontFamily="monospace"
        >
          {"</>"}
        </text>
        <text
          x="710"
          y="190"
          fill={theme.imageHighlight}
          fontSize="22"
          opacity="0.38"
          fontFamily="monospace"
        >
          {"()"}
        </text>
      </svg>
    );
  }
}
